#
# Chart.yaml
#
annotations:
  category: Analytics
  images: |
    - name: gitea
      image: docker.io/bitnami/gitea:1.20.5-debian-11-r6
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r90
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.20.5
dependencies:
- name: replicated
  repository: oci://registry.replicated.com/library
  version: 1.0.0-beta.31
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Gitea is a lightweight code hosting solution. Written in Go, features
  low resource consumption, easy upgrades and multiple databases.
home: https://bitnami.com
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFwAAAAyCAMAAADmz0xAAAAAYFBMVEUAAAD///87OzsNDQ1ycnL7+/t8fHyVlZWDg4NTU1Pr6+vm5uasrKyfn59vb28QEBD19fUiIiLKysrY2Njf39/AwMDQ0NBmZmYdHR2NjY1FRUUpKSm1tbUvLy9AQEBeXl6iWEFiAAADIUlEQVRYha2Y24KrIAxFwXoXrPWuteP//+URIYAalTnTvJRqWEAIO7SEagtK7ieeNyadH0cRZ1PTVnUaBAF1tiAosroqm4nxiFFK4HnbkTN79J9lyDn3w3hYRuWMsZJSxjmPoiEO/bxLktF7949ttwTg9XiKRs1fpnVrrYRHv0MTElL6uHWKV/h5RP4ET8h/sd3g7wXO9bc+ZGXVfg3+IDSDdtLKzXWB+y5wQmiuGgyS0iVxnOBPUuzZerQ/wz9kko3EHDOXvHSCJySUjdbAp2/B8wW/miUQ9bfgA+nXz4+tPt+CM/X5Y2tb8iV4S6TP24YPFx26igbNSMaAPm/hwXJGV7Ph5bn/ID0yj/i38DeFDa2dgg4LXA7HcAvPKaQidwp6oxxCIS7TzzWcUdhSO10oO3EfTbKuta/yr+A1JaBbpQVPT9wrGZPoo8Wi4KfR6UUNfcn2Jl9w7erkS9EhMr7NSXRyAQcp8W/jkq7vKtF82FOpPcy7EXCQRUgzlQ1HU+8LeabjzMK/EfdivVpoFeyMN1b54P7yIp9BVK+8uFqp2HyyGXcCb+QcwR5GchIi1PWF+6TgmXnUcxlY2u+dnyZiyoUTD+B8771GRV6KNgN7Q5Mi7ub8xIDUooEc6ZkCnB4q/mfePYDzk8k5ybSBmSNKVxo4TT/H9xurFCcxQuFDEzlzMohaDq8rp0qkNjQ6keo1IBV92MJpEV7AZV6I6vqGjMzhmFaIf7qDC6E41TmICdE7W+vERzRULXRTJZa1svyQhMIys3EZIFXiY6WlQuHrAqqJx928mZCaSky8Um2mlpfXkQ2XIAQOthHr2ZYSuftyGEzjILUu4Lv7y2wp/pofMiwIewa3Czjdp0/PIFPWBCn0GnamF3kFD45Xk1hpVcrlQFjN0vJwCUcTIbHr4WFxwszbSzh+PTLRQa+Vjel+DT+7ZIQqrEh9y63eN/AAyWIZnSbNJqS6vezf2zdwmrr89LFscxzu4L+kb3b7Hk7T++ustmnb9R5OC/Raglmz6+kAF3rlYq9s388JTtu7Kkg2N7zfwUWBG71zG/0J+8vnHwk1HwIrjV+eAAAAAElFTkSuQmCC
#icon: https://bitnami.com/assets/stacks/gitea/img/gitea-stack-220x234.png
keywords:
- gitea
- analytics
- http
- web
- application
- php
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: gitea
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/gitea
version: 1.0.6